In [11]:
import pandas as pd

trainData = pd.read_csv("Data/KDDcup98/Train/cup98LRN.txt")
"""Selected Features"""
featureList = ['STATE', 'PVASTATE', 'MDMAUD', 'CLUSTER', 'GENDER', 'HIT',
'DATASRCE', 'MALEMILI', 'MALEMILI', 'VIETVETS', 'WWIIVETS', 'LOCALGOV', 'STATEGOV', 
'FEDGOV','CARDPROM', 'NUMPROM', 'RAMNTALL', 'NGIFTALL', 'CARDGIFT', 'AVGGIFT', 'TARGET_D']
trainData = trainData[featureList]
trainData = pd.get_dummies(trainData)

/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [12]:
trainData.head()

HIT  MALEMILI  MALEMILI  VIETVETS  WWIIVETS  LOCALGOV  STATEGOV  FEDGOV  \
0    0         0         0        34        18        10         2       1   
1   16         0         0        55        11         6         2       1   
2    2         0         0        29        33         6         8       1   
3    2         0         0        14        31         3         0       3   
4   60         1         1         9        53        26         3       2   

   CARDPROM  NUMPROM     ...      GENDER_A  GENDER_C  GENDER_F  GENDER_J  \
0        27       74     ...             0         0         1         0   
1        12       32     ...             0         0         0         0   
2        26       63     ...             0         0         0         0   
3        27       66     ...             0         0         1         0   
4        43      113     ...             0         0         1         0   

   GENDER_M  GENDER_U  DATASRCE_   DATASRCE_1  DATASRCE_2  DATASRCE_3  
0         0         0           1           0           0           0  
1         1         0           0           0           0           1  
2         1         0           0           0           0           1  
3         0         0           0           0           0           1  
4         0         0           0           0           0           1  

[5 rows x 168 columns]

In [13]:
import numpy as np
features = np.array(trainData.loc[:, trainData.columns != 'TARGET_D'])

In [14]:
features

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [16.,  0.,  0., ...,  0.,  0.,  1.],
       [ 2.,  0.,  0., ...,  0.,  0.,  1.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 3.,  1.,  1., ...,  0.,  0.,  1.]])

In [15]:
maximum = np.vstack(features.max(axis = 0))
minimum = np.vstack(features.min(axis = 0))

In [16]:
minimum

array([[ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 1.        ],
       [ 4.        ],
       [13.        ],
       [ 1.        ],
       [ 0.        ],
       [ 1.28571429],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0

In [17]:
maximum

array([[2.410e+02],
       [9.900e+01],
       [9.900e+01],
       [9.900e+01],
       [9.900e+01],
       [9.900e+01],
       [9.900e+01],
       [8.700e+01],
       [6.100e+01],
       [1.950e+02],
       [9.485e+03],
       [2.370e+02],
       [4.100e+01],
       [1.000e+03],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],
       [1.000e+00],


In [18]:
maximum - minimum

array([[2.41000000e+02],
       [9.90000000e+01],
       [9.90000000e+01],
       [9.90000000e+01],
       [9.90000000e+01],
       [9.90000000e+01],
       [9.90000000e+01],
       [8.70000000e+01],
       [6.00000000e+01],
       [1.91000000e+02],
       [9.47200000e+03],
       [2.36000000e+02],
       [4.10000000e+01],
       [9.98714286e+02],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
